### ISSUE TITLE
Upgrading database error?

### ISSUE THREAD

**Issue by milezzz** [AlphaReign/www-php#11]
Got the scraper working: https://gyazo.com/58aeb59a6e9164fde4a3120a06a73f9c

I check mysql and can see it populating the torrents table. NICE!

Elasticsearch gave me some headaches on install but managed to get it running. It wouldn't seem to bind to 127.0.0.1 so I made it use the server IP. Curl and http tests show as expected: https://gyazo.com/1e743e6bf577593af06351d863328677

...but sadly I still am getting the 'Upgrading database' error that looks to be thrown when the front-end cannot make a connection to elasticsearch.  I verified my settings.php 

`'hosts' => ['xx.xx.xx.xx:9200']`

Anyone run into this or can @Prefinem offer a suggestion what to try next? Or maybe it just takes time to populate?

**Comment by Raxvis** [comment]
Can you give me the full stack trace on the error?

**Comment by milezzz** [comment]
Spent more hours on this today than I care to admit. Decided to try a fresh VM but again elasticsearch is not working correctly with the loader.  

`pm2 log loader`

```
1|loader   |       at ClientRequest.emit (events.js:211:7)
1|loader   |       at Socket.socketErrorListener (_http_client.js:401:9)
1|loader   |       at emitOne (events.js:116:13)
1|loader   |       at Socket.emit (events.js:211:7)
1|loader   |       at emitErrorNT (internal/streams/destroy.js:66:8)
1|loader   |       at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
1|loader   |       at _combinedTickCallback (internal/process/next_tick.js:139:11)
1|loader   |       at process._tickCallback (internal/process/next_tick.js:181:9)
1|loader   | 
1|loader   | Elasticsearch WARNING: 2018-12-06T21:34:25Z
1|loader   |   Unable to revive connection: http://127.0.0.1:9200/
1|loader   | 
1|loader   | Elasticsearch WARNING: 2018-12-06T21:34:25Z
1|loader   |   No living connections
1|loader   | 
```

So it shows ES not listening on localhost but curl says otherwise:

```
curl http://127.0.0.1:9200/
{
  "name" : "mynode1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "0lEEiT0rRdCd-l-6bX48xQ",
  "version" : {
    "number" : "7.0.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "76cefb0",
    "build_date" : "2018-11-13T12:10:18.050782Z",
    "build_snapshot" : false,
    "qualified" : "7.0.0-alpha1",
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.6.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
I tried changing /etc/elasticsearch/elasticsearch.yml `network.host: 0.0.0.0` but same thing.

Pulling my hair out :/

**Comment by milezzz** [comment]
When hitting the web front end:

```
Details
Type: Elasticsearch\Common\Exceptions\Missing404Exception
Code: 404
Message: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [torrents]","resource.type":"index_or_alias","resource.id":"torrents","index_uuid":"_na_","index":"torrents"}],"type":"index_not_found_exception","reason":"no such index [torrents]","resource.type":"index_or_alias","resource.id":"torrents","index_uuid":"_na_","index":"torrents"},"status":404}
File: /var/www/umash.com/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php
Line: 602
```

**Comment by Raxvis** [comment]
So, the mapping isn't there since the scraper isn't able to put the data into elasticsearch.

Is the scraper on the same box?

**Comment by milezzz** [comment]
Correct the ES data directory is 0 bytes. 

`$ sudo ls -al /var/lib/elasticsearch/nodes`
```
drwxr-xr-x 3 elasticsearch elasticsearch 4096 Dec  6 17:26 0
```

Yep, everything is on the same machine. I installed ES with ```sudo apt-get install elasticsearch```

**Comment by milezzz** [comment]
I should point out I am using http (rather than https) and set this in settings.php - but I don't think it makes much difference.

**Comment by milezzz** [comment]
Hmm maybe this helps...I noticed this on loader-out.log:

```
/home/milez/.pm2/logs/loader-out.log last 15 lines:
1|loader   |   status: 400,
1|loader   |   displayName: 'BadRequest',
1|loader   |   message: '[illegal_argument_exception] Action/metadata line [1] contains an unknown parameter [_retry_on_conflict]',
1|loader   |   path: '/_bulk',
1|loader   |   query: {},
1|loader   |   body: 
1|loader   |    { error: 
1|loader   |       { root_cause: [Array],
1|loader   |         type: 'illegal_argument_exception',
1|loader   |         reason: 'Action/metadata line [1] contains an unknown parameter [_retry_on_conflict]' },
1|loader   |      status: 400 },
1|loader   |   statusCode: 400,
1|loader   |   response: '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_retry_on_conflict]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_retry_on_conflict]"},"status":400}',
1|loader   |   toString: [Function],
1|loader   |   toJSON: [Function] }
```

**Comment by Raxvis** [comment]
What version of elasticsearch do you have?

**Comment by milezzz** [comment]
Initially had 6.5.2 but out of desperation tried 7.0.0-alpha1. Oracle Java 1.8.0_191. Here's more details:

```
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "8j_wF4zHROqvSN2oqvrlIQ" : {
      "name" : "anons",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "7.0.0",
      "build_flavor" : "default",
      "build_type" : "deb",
      "build_hash" : "76cefb0",
      "total_indexing_buffer" : 105630924,
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "attributes" : {
        "ml.machine_memory" : "4158062592",
        "xpack.installed" : "true",
        "ml.max_open_jobs" : "20",
        "ml.enabled" : "true"
      },
      "settings" : {
        "pidfile" : "/var/run/elasticsearch/elasticsearch.pid",
        "cluster" : {
          "name" : "elasticsearch"
        },
        "node" : {
          "attr" : {
            "xpack" : {
              "installed" : "true"
            },
            "ml" : {
              "machine_memory" : "4158062592",
              "max_open_jobs" : "20",
              "enabled" : "true"
            }
          },
          "name" : "anons"
        },
        "path" : {
          "data" : [
            "/var/lib/elasticsearch"
          ],
          "logs" : "/var/log/elasticsearch",
          "home" : "/usr/share/elasticsearch"
        },
        "client" : {
          "type" : "node"
        },
        "http" : {
          "type" : "security4",
          "type.default" : "netty4"
        },
        "transport" : {
          "type" : "security4",
          "features" : {
            "x-pack" : "true"
          },
          "type.default" : "netty4"
        },
        "network" : {
          "host" : "127.0.0.1"
        }
      },
      "os" : {
        "refresh_interval_in_millis" : 1000,
        "name" : "Linux",
        "pretty_name" : "Debian GNU/Linux 8 (jessie)",
        "arch" : "amd64",
        "version" : "3.16.0-6-amd64",
        "available_processors" : 2,
        "allocated_processors" : 2
      },
      "process" : {
        "refresh_interval_in_millis" : 1000,
        "id" : 5724,
        "mlockall" : false
      },
      "jvm" : {
        "pid" : 5724,
        "version" : "1.8.0_191",
        "vm_name" : "Java HotSpot(TM) 64-Bit Server VM",
        "vm_version" : "25.191-b12",
        "vm_vendor" : "Oracle Corporation",
        "start_time_in_millis" : 1544138538460,
        "mem" : {
          "heap_init_in_bytes" : 1073741824,
          "heap_max_in_bytes" : 1056309248,
          "non_heap_init_in_bytes" : 2555904,
          "non_heap_max_in_bytes" : 0,
          "direct_max_in_bytes" : 1056309248
        },
        "gc_collectors" : [
          "ParNew",
          "ConcurrentMarkSweep"
        ],
        "memory_pools" : [
          "Code Cache",
          "Metaspace",
          "Compressed Class Space",
          "Par Eden Space",
          "Par Survivor Space",
          "CMS Old Gen"
        ],
        "using_compressed_ordinary_object_pointers" : "true",
        "input_arguments" : [
          "-Xms1g",
          "-Xmx1g",
          "-XX:+UseConcMarkSweepGC",
          "-XX:CMSInitiatingOccupancyFraction=75",
          "-XX:+UseCMSInitiatingOccupancyOnly",
          "-XX:+AlwaysPreTouch",
          "-Xss1m",
          "-Djava.awt.headless=true",
          "-Dfile.encoding=UTF-8",
          "-Djna.nosys=true",
          "-XX:-OmitStackTraceInFastThrow",
          "-Dio.netty.noUnsafe=true",
          "-Dio.netty.noKeySetOptimization=true",
          "-Dio.netty.recycler.maxCapacityPerThread=0",
          "-Dlog4j.shutdownHookEnabled=false",
          "-Dlog4j2.disable.jmx=true",
          "-Djava.io.tmpdir=/tmp/elasticsearch.BIx8rcLu",
          "-XX:+HeapDumpOnOutOfMemoryError",
          "-XX:HeapDumpPath=/var/lib/elasticsearch",
          "-XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log",
          "-XX:+PrintGCDetails",
          "-XX:+PrintGCDateStamps",
          "-XX:+PrintTenuringDistribution",
          "-XX:+PrintGCApplicationStoppedTime",
          "-Xloggc:/var/log/elasticsearch/gc.log",
          "-XX:+UseGCLogFileRotation",
          "-XX:NumberOfGCLogFiles=32",
          "-XX:GCLogFileSize=64m",
          "-Dio.netty.allocator.type=unpooled",
          "-Des.path.home=/usr/share/elasticsearch",
          "-Des.path.conf=/etc/elasticsearch",
          "-Des.distribution.flavor=default",
          "-Des.distribution.type=deb"
        ]
      },
      "thread_pool" : {
        "watcher" : {
          "type" : "fixed",
          "size" : 10,
          "queue_size" : 1000
        },
        "force_merge" : {
          "type" : "fixed",
          "size" : 1,
          "queue_size" : -1
        },
        "security-token-key" : {
          "type" : "fixed",
          "size" : 1,
          "queue_size" : 1000
        },
        "ml_datafeed" : {
          "type" : "fixed",
          "size" : 20,
          "queue_size" : 200
        },
        "fetch_shard_started" : {
          "type" : "scaling",
          "core" : 1,
          "max" : 4,
          "keep_alive" : "5m",
          "queue_size" : -1
        },
        "listener" : {
          "type" : "fixed",
          "size" : 1,
          "queue_size" : -1
        },
        "ml_autodetect" : {
          "type" : "fixed",
          "size" : 80,
          "queue_size" : 80
        },
        "refresh" : {
          "type" : "scaling",
          "core" : 1,
          "max" : 1,
          "keep_alive" : "5m",
          "queue_size" : -1
        },
        "generic" : {
          "type" : "scaling",
          "core" : 4,
          "max" : 128,
          "keep_alive" : "30s",
          "queue_size" : -1
        },
        "rollup_indexing" : {
          "type" : "fixed",
          "size" : 4,
          "queue_size" : 4
        },
        "warmer" : {
          "type" : "scaling",
          "core" : 1,
          "max" : 1,
          "keep_alive" : "5m",
          "queue_size" : -1
        },
        "search" : {
          "type" : "fixed_auto_queue_size",
          "size" : 4,
          "queue_size" : 1000
        },
        "ccr" : {
          "type" : "fixed",
          "size" : 32,
          "queue_size" : 100
        },
        "flush" : {
          "type" : "scaling",
          "core" : 1,
          "max" : 1,
          "keep_alive" : "5m",
          "queue_size" : -1
        },
        "fetch_shard_store" : {
          "type" : "scaling",
          "core" : 1,
          "max" : 4,
          "keep_alive" : "5m",
          "queue_size" : -1
        },
        "management" : {
          "type" : "scaling",
          "core" : 1,
          "max" : 5,
          "keep_alive" : "5m",
          "queue_size" : -1
        },
        "ml_utility" : {
          "type" : "fixed",
          "size" : 80,
          "queue_size" : 500
        },
        "get" : {
          "type" : "fixed",
          "size" : 2,
          "queue_size" : 1000
        },
        "analyze" : {
          "type" : "fixed",
          "size" : 1,
          "queue_size" : 16
        },
        "write" : {
          "type" : "fixed",
          "size" : 2,
          "queue_size" : 200
        },
        "snapshot" : {
          "type" : "scaling",
          "core" : 1,
          "max" : 1,
          "keep_alive" : "5m",
          "queue_size" : -1
        },
        "search_throttled" : {
          "type" : "fixed_auto_queue_size",
          "size" : 1,
          "queue_size" : 100
        }
      },
      "transport" : {
        "bound_address" : [
          "127.0.0.1:9300"
        ],
        "publish_address" : "127.0.0.1:9300",
        "profiles" : { }
      },
      "http" : {
        "bound_address" : [
          "127.0.0.1:9200"
        ],
        "publish_address" : "127.0.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      },
      "plugins" : [ ],
      "modules" : [
        {
          "name" : "aggs-matrix-stats",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Adds aggregations whose input are a list of numeric fields and output includes a matrix.",
          "classname" : "org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "analysis-common",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Adds \"built in\" analyzers to Elasticsearch.",
          "classname" : "org.elasticsearch.analysis.common.CommonAnalysisPlugin",
          "extended_plugins" : [
            "lang-painless"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "ingest-common",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Module for ingest processors that do not require additional security permissions or have large dependencies and resources",
          "classname" : "org.elasticsearch.ingest.common.IngestCommonPlugin",
          "extended_plugins" : [
            "lang-painless"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "lang-expression",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Lucene expressions integration for Elasticsearch",
          "classname" : "org.elasticsearch.script.expression.ExpressionPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "lang-mustache",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Mustache scripting integration for Elasticsearch",
          "classname" : "org.elasticsearch.script.mustache.MustachePlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "lang-painless",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "An easy, safe and fast scripting language for Elasticsearch",
          "classname" : "org.elasticsearch.painless.PainlessPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "mapper-extras",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Adds advanced field mappers",
          "classname" : "org.elasticsearch.index.mapper.MapperExtrasPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "parent-join",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "This module adds the support parent-child queries and aggregations",
          "classname" : "org.elasticsearch.join.ParentJoinPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "percolator",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Percolator module adds capability to index queries and query these queries by specifying documents",
          "classname" : "org.elasticsearch.percolator.PercolatorPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "rank-eval",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "The Rank Eval module adds APIs to evaluate ranking quality.",
          "classname" : "org.elasticsearch.index.rankeval.RankEvalPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "reindex",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "The Reindex module adds APIs to reindex from one index to another or update documents in place.",
          "classname" : "org.elasticsearch.index.reindex.ReindexPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "repository-url",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Module for URL repository",
          "classname" : "org.elasticsearch.plugin.repository.url.URLRepositoryPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "transport-netty4",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Netty 4 based transport implementation",
          "classname" : "org.elasticsearch.transport.Netty4Plugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-ccr",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - CCR",
          "classname" : "org.elasticsearch.xpack.ccr.Ccr",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-core",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Core",
          "classname" : "org.elasticsearch.xpack.core.XPackPlugin",
          "extended_plugins" : [ ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-deprecation",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Deprecation",
          "classname" : "org.elasticsearch.xpack.deprecation.Deprecation",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-graph",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Graph",
          "classname" : "org.elasticsearch.xpack.graph.Graph",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-ilm",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Index Lifecycle Management",
          "classname" : "org.elasticsearch.xpack.indexlifecycle.IndexLifecycle",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-logstash",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Logstash",
          "classname" : "org.elasticsearch.xpack.logstash.Logstash",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-ml",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Machine Learning",
          "classname" : "org.elasticsearch.xpack.ml.MachineLearning",
          "extended_plugins" : [
            "x-pack-core",
            "lang-painless"
          ],
          "has_native_controller" : true
        },
        {
          "name" : "x-pack-monitoring",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Monitoring",
          "classname" : "org.elasticsearch.xpack.monitoring.Monitoring",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-rollup",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Rollup",
          "classname" : "org.elasticsearch.xpack.rollup.Rollup",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-security",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Security",
          "classname" : "org.elasticsearch.xpack.security.Security",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-sql",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "The Elasticsearch plugin that powers SQL for Elasticsearch",
          "classname" : "org.elasticsearch.xpack.sql.plugin.SqlPlugin",
          "extended_plugins" : [
            "x-pack-core",
            "lang-painless"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-upgrade",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Upgrade",
          "classname" : "org.elasticsearch.xpack.upgrade.Upgrade",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        },
        {
          "name" : "x-pack-watcher",
          "version" : "7.0.0-alpha1",
          "elasticsearch_version" : "7.0.0",
          "java_version" : "1.8",
          "description" : "Elasticsearch Expanded Pack Plugin - Watcher",
          "classname" : "org.elasticsearch.xpack.watcher.Watcher",
          "extended_plugins" : [
            "x-pack-core"
          ],
          "has_native_controller" : false
        }
      ],
      "ingest" : {
        "processors" : [
          {
            "type" : "append"
          },
          {
            "type" : "bytes"
          },
          {
            "type" : "convert"
          },
          {
            "type" : "date"
          },
          {
            "type" : "date_index_name"
          },
          {
            "type" : "dissect"
          },
          {
            "type" : "dot_expander"
          },
          {
            "type" : "drop"
          },
          {
            "type" : "fail"
          },
          {
            "type" : "foreach"
          },
          {
            "type" : "grok"
          },
          {
            "type" : "gsub"
          },
          {
            "type" : "join"
          },
          {
            "type" : "json"
          },
          {
            "type" : "kv"
          },
          {
            "type" : "lowercase"
          },
          {
            "type" : "pipeline"
          },
          {
            "type" : "remove"
          },
          {
            "type" : "rename"
          },
          {
            "type" : "script"
          },
          {
            "type" : "set"
          },
          {
            "type" : "set_security_user"
          },
          {
            "type" : "sort"
          },
          {
            "type" : "split"
          },
          {
            "type" : "trim"
          },
          {
            "type" : "uppercase"
          },
          {
            "type" : "urldecode"
          }
        ]
      }
    }
  }
}
```

**Comment by milezzz** [comment]
Can you tell me what version of ES works, I will uninstall 7.0.0-alpha1 and try installing it from source rather than apt-get.

**Comment by milezzz** [comment]
Reinstalled 6.5.2. Everything works but I suspect the issue was not making loader.js +x - not sure how I missed that. DOH! Can close this thread, thanks so much for @Prefinem hand holding me =]

**Comment by Raxvis** [comment]
Glad to hear you got it fixed!
